# sonarqube/sonar-project.properties
sonar.projectKey=wordpress-ci-cd
sonar.projectName=WordPress CI/CD Pipeline
sonar.projectVersion=1.0

sonar.sources=wordpress/
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.min.js,**/*.min.css

sonar.php.tests.reportPath=reports/phpunit.xml
sonar.php.coverage.reportPaths=reports/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=${SONAR_TOKEN}

# Reglas PHP
sonar.php.file.suffixes=php
sonar.php.coverage.reportPaths=reports/coverage.xml
